// dom = document object model
//if we want to modify (add delete or any thing) in html by javascript then we do it by dom 
//we can even add or remove css in html by dom 
//evry element (tag) is known as node in dom
// if we are targeting text in html it is known as text node in dom
// evry thig is object in dom 

//===================================================  6 oct ======================================================================

// document.getElementById('head').textContent = "i"
 // document.getElementById('head').removeAttribute('style')
// document.getElementById('head2').textContent = "am"
// document.getElementById('head3').textContent = "from"
// document.getElementById('head4').textContent = "rewa"
// document.getElementById('head5').textContent = "in"
// document.getElementById('head6').textContent = "mp"


// let a = document.getElementById('demo')
// a.textContent = "another way"

// let b = document.getElementById('lily')
// b.innerHTML = "<i> lily bhai </i>"

// let c = document.getElementById('class')
// c.innerHTML = " <u> shivanshu bhaiya </u> "
// c.setAttribute('align' , 'center')

// document.body.setAttribute('bgcolor' , 'pink')

let d = document.getElementById('shiva')
d.setAttribute('src','photo123.jpg')