//if we want to apply single line of js
// document.getElementById('head').style.backgroundColor="yellow"

// if we want to apply multiple line of js
// let head = document.getElementById('demo')
// head.style.backgroundColor="lightblue"
// head.style.padding="20px"

//task
// let head = document.getElementById('kamal')
// head.style.backgroundColor="lightblue"
// head.style.padding="20px"


// let shiv = document.getElementById('kamal2')
// shiv.style.backgroundColor="pink"
// shiv.style.padding="50px"
// shiv.style.fontSize="30px"

// using multiple element of css
// let head1 = document.getElementById('rahul')
// head1.style.cssText = "background-color:red;color:white;padding:20px"

//element mtlb tag
// let tag = document.createElement('h1')
// tag.textContent="new element from js"
// console.log(tag);

// document.getElementById('parent').append(tag)


let para=document.createElement('p')
para.textContent="a new message"
document.getElementById('parent1').append(para)







