// Document.getElementById('image').src=""


//============================================EVENTS==========================================
//events are called action which change perform by user of webpage

// function fun()
// {
// alert("hello....")
// }

// on single click

// function red(){
//     document.body.style.backgroundColor="red"
// }
// function blue(){
//     document.body.style.backgroundColor="blue"
// }
// function green(){
//     document.body.style.backgroundColor="green"
// }function black(){
//     document.body.style.backgroundColor="black"
// }



//on multiple click
// function color(mc){
//     document.body.style.backgroundColor = mc
// }

// function fun1()
// {
//     document.getElementById("rahul").textContent="shiva is here"
// }


//==================================================================================================

// let h = document.getElementsByTagName('h1')
// console.log(h[0]);
// h[0].style.color="red"



// let h = document.getElementsByTagName('h2')
// console.log(h[0]);
// h[0].style.color="red"
// h[1].style.color="blue"
// h[2].style.color="green"
// h[3].style.color="yellow"
// h[4].style.color="pink"
// h[5].style.color="lightblue"


// let s = document.getElementsByClassName('head')
// console.log(s[0]);
// s[0].style.color="red"
// s[1].style.color="blue"
// s[2].style.color="green"
// s[3].style.color="yellow"

//======================================================================================================
//  query selector---------------------->  single element target
// queryselectorAll ------------------>target multiple tag id class mtlb sbhi trah ke element target kar sakte hai
//  class=== .classname
//  id ===  #idname
//  tag ===  tagname
//==============================================
// let h = document.querySelector('.shiv')
// h.style.backgroundColor='pink'
// h.style.color='red'

//============================================================

// function fun(){
//     document.querySelector('.shiv').src=''
//     let a = document.querySelector('.shi')
//    a.textContent='bike'
//    a.style.color='red'
// }
// function fun1(){
//     document.querySelector('.shiv').src=''
//    let a = document.querySelector('.shi')
//    a.textContent='car'
//    a.style.color='green'
// }
// function fun2(){
//     document.querySelector('.shiv').src=''
//     let a = document.querySelector('.shi')
//    a.textContent='train'
//    a.style.color='blue'
// }

//====================================13.10.25=======================================
// function fun(){
// let wrapper = document.querySelector('#container')
// wrapper.classList.add('wrapper')
// }

// function remov(){
// let container = document.querySelector('#container')
// container.classList.remove('wrapper')
// }

// function both(){
//     let cn = document.querySelector('#container')
//     cn.classList.toggle('wrapper')
// }


//=======

// function theme(){
//     let an = document.body.classList.toggle('theme')
    

// if(an==true){
//     document.querySelector('#btn').textContent="light"
// }
// else{
//      document.querySelector('#btn').textContent="dark"
// }
// }

//=================================================14.10.25==================================================
//===================================callback function======================================